### ISSUE TITLE
errors in cygwin installation

### ISSUE THREAD

**Issue by metzgerm** [gmarcais/Jellyfish#101]
I am compiling Jellyfish on a windows machine using cygwin64 (with gcc, g++, and make installed). The ./configure command appeared to work but I get errors with the next command in the process (pasted below). Trying $ make install gives the same errors. Does anyone have any ideas (other than getting a linux machine instead).

Thanks,
Michael

$ make -j 4
make  all-am
make[1]: Entering directory '/cygdrive/c/Users/Michael/Desktop/jellyfish-2.2.7'
  CXX      lib/rectangular_binary_matrix.lo
  CXX      lib/mer_dna.lo
  CXX      lib/storage.lo
  CXX      lib/allocators_mmap.lo
lib/rectangular_binary_matrix.cc: In static member function ‘static uint64_t* jellyfish::RectangularBinaryMatrix::alloc(unsigned int, unsigned int)’:
lib/rectangular_binary_matrix.cc:34:81: error: ‘posix_memalign’ was not declared in this scope
   if(posix_memalign(&mem, sizeof(uint64_t) * 2, alloc_columns * sizeof(uint64_t)))
                                                                                 ^
make[1]: *** [Makefile:1656: lib/rectangular_binary_matrix.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/cygdrive/c/Users/Michael/Desktop/jellyfish-2.2.7'
make: *** [Makefile:966: all] Error 2

**Comment by metzgerm** [comment]
I just realized there was a previous post on this same issue with the earlier version (2.2.6). I have not seen any posted reply, but I get essentially the same error with 2.2.7.

**Comment by gmarcais** [comment]
You can compile by configuring like this: `./configure CXXFLAGS=-std=gnu++11`. It will be automatic in the next release. Thanks for the bug report.

**Comment by zhangjiezk** [comment]
when perfor command "make check" present error jellyfish/dbg.cc:19:25: 致命错误：sys/syscall.h：No such file or directory
 #include <sys/syscall.h>
Does anyone have any ideas about it ?
