### ISSUE TITLE
jellyfish count database format

### ISSUE THREAD

**Issue by rfm-targa** [gmarcais/Jellyfish#104]
Greetings,

I'm working in taxonomic classification and a program I'm using uses Jellyfish 1. The program doesn't support Jellyfish 2 and I think it's because the output file of the count function has changed from Jellyfish 1 to 2. Could anyone tell me what exactly changed in the output of the count function?
Is it possible to make the count function output of Jellyfish 2 equal to that of Jellyfish 1?

Thanks in advance!

**Comment by gmarcais** [comment]
The main change is in the header. The header of JF1 was binary and fixed length. The header of JF2 is in json and variable length. The rest should be the same, provided the k-mer length is below 31 bits.

There is no command provided right now to change the format from one to the other.

**Comment by rfm-targa** [comment]
Thank you very much for the reply, this helps.
