### ISSUE TITLE
Help: Jellyfish Configurations

### ISSUE THREAD

**Issue by taranglute** [gmarcais/Jellyfish#106]
Hi

We are working on analysis of Bioinformatics tools (related to Kmer counting) and Jellyfish is one of them. We have gone through **readme** file and it is very helpful. As we are doing analysis so we want to be very sure about details. It would be great if you help us validating below details.

**Data structure and Sorting Algo:** Hash Table/ Hashing,Bloom filter
**Approach:** Multi-threaded using compare and swap operation
**The limit of k-size** : less than 500 (NOT SURE)
**Supports online k-mer frequency retrieval** : Yes
**Supports compressed file processing** : No

**Query**
Which approach Jellyfish use for kmer counting 
1. Disk based
2. In memory
 
Thanks
Tarang

**Comment by gmarcais** [comment]
limit of k-size: no real limit.
compressed file processing: yes in the later version.
approach: mostly in memory. Uses disk if memory fills up
