### ISSUE TITLE
2.1.2 is not buildable

### ISSUE THREAD

**Issue by moskalenko** [gmarcais/Jellyfish#11]
Hi,

I noticed that 2.1.2 release was pushed two hours ago, so I tried to build it. However, there is an autotools problem. Configuration scripts are missing. After an autoreconf run followed by configure there is still an issue:

$ make
make: **\* No rule to make target `false', needed by`sub_commands/count_main_cmdline.hpp'.  Stop.

**Comment by cboursnell** [comment]
I ran this
```shell
git clone git@github.com:gmarcais/Jellyfish.git
cd Jellyfish/
autoreconf -i
mkdir build
cd build
 ../configure 
make
```
and I get 
`make: *** No rule to make target `false', needed by `sub_commands/count_main_cmdline.hpp'.  Stop.`
I'm on Debian wheezy with g++ (Debian 4.7.2-5) 4.7.2 and ldd (Debian EGLIBC 2.13-38+deb7u1) 2.13

**Comment by gmarcais** [comment]
On Fri, Mar 20, 2015 at 1:15 PM, Chris Boursnell <notifications@github.com>
wrote:

> I ran this
>
> git clone git@github.com:gmarcais/Jellyfish.gitcd Jellyfish/
> autoreconf -i
> mkdir buildcd build
>  ../configure
> make
>
> and I get
> make: *** No rule to make targetfalse', needed by sub_commands/count_main_cmdline.hpp'.
> Stop.
> I'm on Debian wheezy with g++ (Debian 4.7.2-5) 4.7.2 and ldd (Debian
> EGLIBC 2.13-38+deb7u1) 2.13
>

Do you have Yaggo installed? It is required when working from the git tree.
Use the tarballs provided from the jellyfish webpage to get a package
depending only on make and g++.

Guillaume.
