### ISSUE TITLE
Missing configure script in the 2.2.9 source release

### ISSUE THREAD

**Issue by blaiseli** [gmarcais/Jellyfish#113]
I downloaded the source (https://github.com/gmarcais/Jellyfish/archive/v2.2.9.tar.gz) and tried to follow the compilation instructions found here: https://github.com/gmarcais/Jellyfish

These instructions fail because there is no configure script in the tar archive.

**Comment by cjieming** [comment]
I am seeing this too. Can somebody comment on this too please? thanks.

**Comment by cjieming** [comment]
oh i just realize there's a section in the README.md that talks about the difference when you clone it from GitHub, instead of the tarball. @blaiseli , maybe you can try that.

**Comment by vsivsi** [comment]
I'm seeing this too. No `configure` script in the tarball.

**Comment by gmarcais** [comment]
Please, download the source distribution tarball (https://github.com/gmarcais/Jellyfish/releases/download/v2.2.9/jellyfish-2.2.9.tar.gz), not the automatically generated link of Github below that.

<rant>Please, github, do not generate those links. They are useless and cause confusion</rant>
