### ISSUE TITLE
Error: Only even kmers in hist file

### ISSUE THREAD

**Issue by pminx** [gmarcais/Jellyfish#114]
Hi,

I must be running multiple fastq files incorrectly in jellyfish. In my output .hist file I only get even kmers. Below are my commandlines and at the bottom is an example of one of my hist files. Should I be combining (shuffling) my 1&2s fastqs first? Can someone tell me what I'm doing wrong?

Thanks,

Pat

jellyfish count -C -m 21 -s 90000000000 -t 24  HF27HBBXX_CACGTCTA_1_sequence.fastq HF27HBBXX_CACGTCTA_2_sequence.fastq -o HF27HBBXX_3_reads.jf

jellyfish histo -t 24 HF27HBBXX_3_reads.jf > HF27HBBXX_3_reads.hist

> 2 2428477947
> 4 94227510
> 6 14722302
> 8 5524970
> 10 2869024
> 12 1776189
> 14 1197518
> 16 862478
> 18 649496
> 20 504531

**Comment by gmarcais** [comment]
That looks strange indeed. Are you sure that the 2 input files HF27HBBXX_CACGTCTA_1_sequence.fastq  and HF27HBBXX_CACGTCTA_2_sequence.fastq are different?
