### ISSUE TITLE
make check error

### ISSUE THREAD

**Issue by cjieming** [gmarcais/Jellyfish#115]
Hi @gmarcais 

I am having issue installing jellyfish 2.2.9 (make error on first line), but end up being able to run 2.2.6 that is actually sufficient for a particular software that depends on jellyfish.

However, I ran into an error when I ran `make check`:

> make check
> make  check-am
> make[1]: Entering directory `/gnet/is2/p01/home/chenj220/software/jellyfish-2.2.6'
> make  libgtest.la libgtest_main.la bin/generate_sequence bin/test_all
> make[2]: Entering directory `/gnet/is2/p01/home/chenj220/software/jellyfish-2.2.6'
>   CXX      unit_tests/gtest/src/libgtest_la-gtest-all.lo
> /gnet/is2/p01/apps/gcc/4.9/x86_64-linux-2.6-rhel6/bin/../libexec/gcc/x86_64-unknown-linux-gnu/4.9.0/cc1plus: error while loading shared libraries: libmpc.so.3: cannot open shared object file: No such file or directory
> make[2]: *** [unit_tests/gtest/src/libgtest_la-gtest-all.lo] Error 1
> make[2]: Leaving directory `/gnet/is2/p01/home/chenj220/software/jellyfish-2.2.6'
> make[1]: *** [check-am] Error 2
> make[1]: Leaving directory `/gnet/is2/p01/home/chenj220/software/jellyfish-2.2.6'
> make: *** [check] Error 2

That said, I was able to do `jellyfish --version` and `jellyfish count` etc. Does the `make check` signify a deeper issue that I shouldn't use the jellyfish as is and resolve that error first? How do I resolve that error? 

Thank you!

**Comment by gmarcais** [comment]
The compilation error seems to occur within your own compiler: it fails to load the GNU MPC library. This library is NOT used by jellyfish itself.

Why the compiler works fine to compile the program jellyfish and not the testing, I don't know. But the resulting program should be alright.
