### ISSUE TITLE
Building jellyfish on mac

### ISSUE THREAD

**Issue by SteveGoldstein** [gmarcais/Jellyfish#116]
I can't build jellyfish on my mac:  High Sierra 10.13.3.  

I tried 
     sudo port install gcc48
as per the README.  It failed with this error:

Error: gcc48 is not supported on macOS High Sierra and newer
Error: Failed to fetch gcc48: unsupported platform

Do you have a set of MacOS binaries that I could use?

**Comment by gmarcais** [comment]
I need to update the documentation. On High Sierra, the compiler is recent enough to compile Jellyfish. You should be able to compile directly with the built-in compile.

The latest release has a bug mac and doesn't compile. I would use version 2.2.7 or wait for the next release (hopefully today), which will also come with binaries.
