### ISSUE TITLE
jellyfish version 1

### ISSUE THREAD

**Issue by chloelulu** [gmarcais/Jellyfish#120]
Hi, 
I need jellyfish version 1 to run on the kraken software. However, I installed the old version from http://www.cbcb.umd.edu/software/jellyfish/ 
However, after I finish installation according to the http://www.cbcb.umd.edu/software/jellyfish/README 
jellyfish --version
I got jellyfish jellyfish v2.2.3

May I know how can I install the jellyfish version 1? 
Thanks

**Comment by mmokrejs** [comment]
http://www.cbcb.umd.edu/software/jellyfish/jellyfish-1.1.11.tar.gz
http://www.cbcb.umd.edu/software/jellyfish/jellyfish-manual-1.1.pdf

**Comment by chloelulu** [comment]
Hi, @mmokrejs ,

Thanks for the reply. However, I used the source you provided, and ./configure, make, make install. The final version is still jellyfish 2.2.3. How can I achive the jellyfish 1?

**Comment by gmarcais** [comment]
An updated version to version 1 has been [released](https://github.com/gmarcais/Jellyfish/releases/tag/v1.1.12). No new features, only maintenance.
