### ISSUE TITLE
making jellyfish-1.1.11 sources C++14 compatible

### ISSUE THREAD

**Issue by mmokrejs** [gmarcais/Jellyfish#122]
Hi,
  I am trying to compile quorum-0.2.1 which relies on jellyfish1. I attach the build log file. It seems the issue is with jellyfish1 headers, not with quorum itself. I use gcc-7.3.0.

[build.log.txt](https://github.com/gmarcais/Jellyfish/files/1934542/build.log.txt)

**Comment by gmarcais** [comment]
Please, try the new [release version 1.1.12](https://github.com/gmarcais/Jellyfish/releases/tag/v1.1.12), it should fix those issues.

Now, I am curious why you are using version 0.2.1 of Quorum, instead of the latest one?

**Comment by mmokrejs** [comment]
Hm, good point. I went to update existing package definition files in Gentoo so ... for historical reasons. I will drop this old version, there is latest already in the tree anyway.
