### ISSUE TITLE
fails to configure

### ISSUE THREAD

**Issue by ReJun** [gmarcais/Jellyfish#126]
autoreconf -i
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
configure.ac:9: error: possibly undefined macro: AC_LIB_RPATH
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:32: error: possibly undefined macro: AC_LIB_LINKFLAGS_FROM_LIBS
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by gmarcais** [comment]
Did you try compiling the distribution tar ball [jellyfish-2.2.10.tar.gz](https://github.com/gmarcais/Jellyfish/releases/download/v1.1.12/jellyfish-1.1.12.tar.gz). It does not require any of the autoconf suite, simply untar and then `./configure && make`.

You only need to run `autoreconf -fi` if you compile directly from the github development tree.

What version of autoconf, automake and libtoolize do you use?

**Comment by gmarcais** [comment]
I was able to reproduce the problem.

Let me first say that you should use the distribution tar ball as pointed above. It has much fewer dependencies.

If you need to compile from the git repository, you additionally need the packages gettext, pkg-config and yaggo.

**Comment by ReJun** [comment]
nice！thank you for your reply.

**Comment by outpaddling** [comment]
Same problem here.  I have all the dependencies installed per the build instructions.

And FYI, your link above points to the 1.1.12 release, although the text says 2.2.10.

I was able to work around the issue by hard-coding the URL as you suggested, but I'd be interesting in knowing the solution to the autoreconf issue.  I'm building on CentOS under pkgsrc.

===> Installing dependencies for Jellyfish-2.2.10
=> Tool dependency libtool-base>=2.4.2nb9: found libtool-base-2.4.6nb1
=> Tool dependency automake>=1.9: found automake-1.15.1
=> Tool dependency autoconf>=2.58: found autoconf-2.69nb7
=> Tool dependency pkgconf-[0-9]*: found pkgconf-1.4.1nb1
=> Tool dependency checkperms>=1.1: found checkperms-1.12
=> Build dependency gcc5>=5.5.0: found gcc5-5.5.0nb2
=> Build dependency cwrappers>=20150314: found cwrappers-20180325
=> Full dependency yaggo>=0: found yaggo-1.5.9
===> Overriding tools for Jellyfish-2.2.10
===> Extracting for Jellyfish-2.2.10
===> Patching for Jellyfish-2.2.10
=> Applying pkgsrc patches for Jellyfish-2.2.10
===> Creating toolchain wrappers for Jellyfish-2.2.10
===> Configuring for Jellyfish-2.2.10
(cd /usr/pkgsrc/wip/jellyfish2/work/Jellyfish-2.2.10 && autoreconf -i)
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:9: error: possibly undefined macro: AC_LIB_RPATH
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:32: error: possibly undefined macro: AC_LIB_LINKFLAGS_FROM_LIBS
autoreconf: /usr/pkg/bin/autoconf failed with exit status: 1
*** Error code 1
