### ISSUE TITLE
query command functionality

### ISSUE THREAD

**Issue by kes1smmn** [gmarcais/Jellyfish#13]
Dear Guillaume,

Would you consider the following functionality in the query command?  I would like to get the kmers present in each sequence of a multiline fasta and fastq.

Would it be possible to modify the current jellyfish output to have each sequence separated by the read_id or an added first column with the read id. 

OR

even a more simply display
read_id  count_of_kmers_present_in_jellyfish_db

thanks for humoring me. I have a python wrapper that does this by querying each sequence individual but the speed is not as good as I would like.
Keith

**Comment by Earwelen** [comment]
Hi @gmarcais 
Does Jellyfish support kmer counts per read or kmer count for an input (let's say echo ATCGACGTA | jellyfish [...] ?

I saw your comment here stating that Jellyfish won't provide much speed for small files/sequences ?
https://github.com/gmarcais/Jellyfish/issues/23#issuecomment-59966372

**Comment by gmarcais** [comment]
Please, create a new issue for a new unrelated question. See issue #160.
