### ISSUE TITLE
multiple runs of jellyfish produce different results (2.2.10) but consistent in older versions (1.1.11, 2.2.6)

### ISSUE THREAD

**Issue by bwlang** [gmarcais/Jellyfish#133]
When I run the latest jellyfish (either from bioconda or from https://github.com/gmarcais/Jellyfish/releases/download/v2.2.10/jellyfish-linux) I get different results each time I run it:  The results are reasonable-ish, but not correct.

e.g. with the github download
for rep in 1 2 3 4 5; do ./jellyfish-linux count -t 16 -m 2 -s 100M 1m.fastq -o testjf2210linux$rep.jf;done
for f in testjf2210linux*.jf; do jellyfish dump -ct $f > $f.tsv;done

I've plotted the results for a couple of different versions for easier comparison:
with the jellyfish-linux binary from github (similar results to conda version)
![image](https://user-images.githubusercontent.com/61636/45464873-93004c80-b6e0-11e8-8585-5c8feb65bcd6.png)

however with 2.2.6 from conda:
![image](https://user-images.githubusercontent.com/61636/45464953-ec687b80-b6e0-11e8-9c96-611c0bdc8f4c.png)

same results as 1.1.11
![image](https://user-images.githubusercontent.com/61636/45464995-1e79dd80-b6e1-11e8-9634-67550ecdb3d5.png)

Interestingly, the lowest frequency mer, GC, is consistent both between reps and with old versions in 2.2.10.  Also - total counts are too small in 2.2.10 (7.3M mers, old versions have 24,104,756)

**Comment by phpeters** [comment]
Hej Brad,

is this still an issue for you? I had a similar problem, getting close-to-correct counts.
Did you try to change the --counter-len parameter to something bigger than default? That helped me. Seems like jellyfish ran out of space for counting.

Best!
Philipp

**Comment by bwlang** [comment]
@phpeters 
I did not try that...  maybe that provides a clue about the source of the bug

**Comment by gmarcais** [comment]
This is fixed in the develop branch, and will be released soon.

**Comment by bwlang** [comment]
@gmarcais 
I tried to find a commit to tie this to but could not find one in the branches i looked at. Did I miss one?

**Comment by gmarcais** [comment]
My bad, it was not pushed to github. 9fb6c3532399d386d6fc8a28293f9b025d08b4b0 is the commit fixing this. I should release v2.3.0 by the end of the week containing this and other fixes.

**Comment by mamora** [comment]
@gmarcais is the version 2.3.0 already released? I am having the same bug with the latest 2.2.10 version
