### ISSUE TITLE
DOS line endings

### ISSUE THREAD

**Issue by sfletc** [gmarcais/Jellyfish#136]
Just noticed that counting kmers in FASTA files with DOS line endings doesn't provide the correct result (version 2.2.10).  As near as I can tell, every kmer that covers a line ending is not counted, and no error is thrown.  Would be nice to either deal with DOS line endings internally, or at least throw an error so unsupecting users can fix their input files with UNIX line endings.

**Comment by gmarcais** [comment]
This is fixed in the develop branch (DOS line endings are supported). It will appear in master and the next distribution shortly.
