### ISSUE TITLE
How to get the version of jellyfish

### ISSUE THREAD

**Issue by bhishanpdl** [gmarcais/Jellyfish#194]
I was tying to see what version of jellyfish is installed in my machine.
I used the following command:

```python
import jellyfish
print(f"jellyfish: {jellyfish.__version__}")

But, I get this error:

AttributeError: module 'jellyfish' has no attribute '__version__'

```

How to get the version of jellyfish?

**Comment by gmarcais** [comment]
Available in the develop branch. Will be available in 2.4.0
