### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by lufuhao** [gmarcais/Jellyfish#28]
Hi, I got make error when compiling the git version today. Please HELP.
cmd: 

git clone https://github.com/gmarcais/Jellyfish.git
autoreconf -i
./configure --prefix=/path/to/jellyfish/v2.1.4/x86_64
make

CONFIGURE
-----------------------------------------------------------------
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for md5sum... md5sum
checking for yaggo... /usr/users/celldev/luf/local/yaggo/v1.5.4/x86_64/bin/yaggo
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for __int128... yes
checking for std::numeric_limits<__int128>... no
checking for _NSGetExecutablePath... no
checking for execinfo.h... yes
checking for ext/stdio_filebuf.h... yes
checking for siginfo_t.si_int... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating tests/compat.sh
config.status: creating jellyfish-2.0.pc
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
-------------------------------------------------------------

Make error: 
-----------------------------------------------------------------
YAGGO  sub_commands/count_main_cmdline.hpp
  YAGGO  sub_commands/info_main_cmdline.hpp
  YAGGO  sub_commands/dump_main_cmdline.hpp
  YAGGO  sub_commands/histo_main_cmdline.hpp
  YAGGO  sub_commands/stats_main_cmdline.hpp
  YAGGO  sub_commands/merge_main_cmdline.hpp
  YAGGO  sub_commands/bc_main_cmdline.hpp
  YAGGO  sub_commands/query_main_cmdline.hpp
  YAGGO  sub_commands/cite_main_cmdline.hpp
  YAGGO  sub_commands/mem_main_cmdline.hpp
  YAGGO  jellyfish/generate_sequence_cmdline.hpp
  YAGGO  unit_tests/test_main_cmdline.hpp
make  all-am
make[1]: Entering directory `/usr/users/celldev/luf/local/jellyfish/v2.1.4/Jellyfish'
  
CXX      lib/rectangular_binary_matrix.lo
 
CXX      lib/mer_dna.lo
  
CXX      lib/storage.lo
  
CXX      lib/allocators_mmap.lo
  
CXX      lib/misc.lo
  
CXX      lib/int128.lo
  
CXX      lib/thread_exec.lo
  
CXX      lib/jsoncpp.lo
  
CXX      lib/time.lo
  
CXX      lib/generator_manager.lo
  
CXX      sub_commands/jellyfish.o
 
CXX      sub_commands/count_main.o

sub_commands/jellyfish.cc: In function ‘int version(int, char**)’:

sub_commands/jellyfish.cc:130:16: error: ‘PACKAGE_STRING’ was not declared in this scope
   std::cout << PACKAGE_STRING << std::endl;
                ^

make[1]: *** [sub_commands/jellyfish.o] Error 1

make[1]: *** Waiting for unfinished jobs....

make[1]: Leaving directory `/usr/users/celldev/luf/local/jellyfish/v2.1.4/Jellyfish'

make: *** [all] Error 2
--------------------------------------------------------

**Comment by lufuhao** [comment]
Plus: ubuntu 14.04 x86_64
gcc 4.9.2
g++ 4.9.2

**Comment by gmarcais** [comment]
I don't understand how PACKAGE_STRING can be undefined. Configure is setting this in config.h. Can you apply this patch?

https://gist.github.com/440d5491de5c4cfb7d03.git

Let me know if this works for you.
