### ISSUE TITLE
Update Jellyfish releases on Github - genome.umd.edu unavailable

### ISSUE THREAD

**Issue by DanTheColoradan** [gmarcais/Jellyfish#31]
I'm unable to access the genome subdomain for UMD. Could you put version 2.2.0 tar.gz / zip on github as well? Or any newer version should work as well.

**Comment by gmarcais** [comment]
Here is the reason:

http://www.nbcwashington.com/news/local/Scattered-Power-Outages-Reported-in-Across-DC-Area-298923411.html

I am not the one in charge of the webserver machine, but it seems its power
backup is not up to snuff. I'll look at putting the tarball on github, when
I can access my machines again :)

Guillaume.

**Comment by DanTheColoradan** [comment]
Thanks! I didn't imagine you would be in charge :D Hopefully github will be a bit more robust once you get it up here ;-)
