### ISSUE TITLE
jellyfish count returns empty file when using --min-qual-char on fasta file

### ISSUE THREAD

**Issue by dkoslicki** [gmarcais/Jellyfish#35]
It appears that jellyfish (version 2.1.1) fails when using the flag ``--min-qual-char`` on a fasta file. For example, 
``jellyfish count test.fasta -m 20 -s 100M -t 20 -Q C -o test.jf``
results in file ``test.jf`` with no kmers in it.

Perhaps it would be better for jellyfish to either throw an error when combining ``-Q`` with a fasta file, or else simply ignore the ``-Q`` flag (I think the latter might be better).

**Comment by gmarcais** [comment]
This is fixed. -Q has no effect on fasta files now. See latest release v2.2.3.

Thanks for the bug report.
