### ISSUE TITLE
error in building

### ISSUE THREAD

**Issue by kengcher** [gmarcais/Jellyfish#51]
I ran into this error while building jellyfish on my linux system: 

build> make
  YAGGO    sub_commands/count_main_cmdline.hpp
  YAGGO    sub_commands/info_main_cmdline.hpp
  YAGGO    sub_commands/dump_main_cmdline.hpp
  YAGGO    sub_commands/histo_main_cmdline.hpp
  YAGGO    sub_commands/stats_main_cmdline.hpp
  YAGGO    sub_commands/merge_main_cmdline.hpp
  YAGGO    sub_commands/bc_main_cmdline.hpp
  YAGGO    sub_commands/query_main_cmdline.hpp
  YAGGO    sub_commands/cite_main_cmdline.hpp
  YAGGO    sub_commands/mem_main_cmdline.hpp
  YAGGO    jellyfish/generate_sequence_cmdline.hpp
  YAGGO    unit_tests/test_main_cmdline.hpp
make  all-am
make[1]: Entering directory `/local0/sw/Jellyfish/build'
  CXX      lib/rectangular_binary_matrix.lo
  CXX      lib/mer_dna.lo
  CXX      lib/storage.lo
  CXX      lib/allocators_mmap.lo
  CXX      lib/misc.lo
../lib/misc.cc: In function ‘std::string jellyfish::quote_arg(const std::string&)’:
../lib/misc.cc:86: error: ‘all_of’ is not a member of ‘std’
make[1]: *** [lib/misc.lo] Error 1
make[1]: Leaving directory `/local0/sw/Jellyfish/build'
make: *** [all] Error 2

Pls kindly advise how can i resolve it.

Thank you.

**Comment by kengcher** [comment]
Just realized that I was using an old gcc. Updated that and it works now.

**Comment by gmarcais** [comment]
Great. Glad it works for you.
