### ISSUE TITLE
Parser interprets empty read as end-of-file

### ISSUE THREAD

**Issue by rob-p** [gmarcais/Jellyfish#55]
Hi Guillaume,

  @roryk noticed this issue in RapMap (https://github.com/COMBINE-lab/RapMap/issues/19), and has a nice sample dataset to reproduce it.  Basically, when a read is empty, but not the actual end of the file, the parser thinks it's done.  Is there an easy way to change the parser logic to account for this situation?

--Rob

**Comment by gmarcais** [comment]
Indeed, that is not good. I'll fix it ASAP.

**Comment by gmarcais** [comment]
Can you try the develop branch? The issue should be fixed.

**Comment by rob-p** [comment]
That *was* fast!  I'll test it out as soon as I get into work.

**Comment by rob-p** [comment]
Here I betray my strong CMake bias — what magical invocations must I make to generate a proper `configure` script?  I tried `aclocal && autoconf && automake --add-missing`.

**Comment by gmarcais** [comment]
The magic call is:

```
echo abracadabra; autorecof -fi
```

**Comment by gmarcais** [comment]
Oups, typo, `autoreconf -fi`.

**Comment by rob-p** [comment]
ahhh, see I was missing the `abracadabra` incantation!  Any interest in building a tagged tarball (i.e. with a stable GitHub url) that already has the `./configure` script ready to go?  Right now I'm pulling from [https://github.com/gmarcais/Jellyfish/archive/develop.zip ](https://github.com/gmarcais/Jellyfish/archive/develop.zip), which, I imagine, is subject to change in content ;P.

**Comment by gmarcais** [comment]
I will do that. I was hoping to get a feed back from you that it indeed fixed the problem before generating a new version and upload it to the [releases](https://github.com/gmarcais/Jellyfish/releases).

**Comment by rob-p** [comment]
I can confirm that this does, indeed, fix the problem (using Rory's test data).  The parser now returns (and RapMap now reports) having observed 5 reads, instead of 0, which is correct.

**Comment by gmarcais** [comment]
OK, the new distribution tarball is ready in the releases(https://github.com/gmarcais/Jellyfish/releases).

Thanks for the bug report.

**Comment by rob-p** [comment]
Fantastic.  Thanks, Guillaume!

**Comment by roryk** [comment]
Thanks!

**Comment by mr-c** [comment]
Is it known how far back this bug has existed?
