### ISSUE TITLE
Python module has name space conflict with jellyfish

### ISSUE THREAD

**Issue by tillea** [gmarcais/Jellyfish#69]
Hi,

there is a name space conflict with [jellyfish](https://github.com/jamesturk/jellyfish).  The Debian maintainer of the latter Python module has provided a [patch](https://anonscm.debian.org/git/debian-med/jellyfish.git/tree/debian/patches/rename-python-module-to-dna_jellyfish.patch) for Jellyfish which is now used inside the Debian packaging.

I wonder whether you might consider taking over this patch into your official source to avoid name space conflicts also for non-Debian users who might like to install both modules on one computer (chances are pretty low but given anyway).

Kind regards

```
      Andreas.
```

**Comment by mmokrejs** [comment]
Hi @tillea , the URL to the patch is now returning 404 error. To which jellyfish versions is it still applicable/relevant? Thank you.

**Comment by tillea** [comment]
Hi,

the last yellyfish changelog in Debian reads:

    jellyfish (2.2.8-1) unstable; urgency=medium
    
      * New upstream version
      * Dropped rename-python-module-to-dna_jellyfish.patch as upstream has
        incorporated it.
    
     -- Michael R. Crusoe <michael.crusoe@gmail.com>  Sun, 11 Feb 2018 09:21:51 -0800

I think you can close that issue, Andreas.
