### ISSUE TITLE
No configure file in the source code?

### ISSUE THREAD

**Issue by chjiao** [gmarcais/Jellyfish#77]
I only see a "configure.ac" file in the source, which always get error when trying to configure. What is the right way to install from source? Thank you.

**Comment by gmarcais** [comment]
The right way is to compile from the release tarball, available from the [release page](https://github.com/gmarcais/Jellyfish/releases). Download the file `jellyfish-x.y.z.tar.gz`, where `x.y.z` is the version.

You can start from the git tree instead, but then you need `autoconf/automake` and `yaggo`. You first need to run `autoreconf -fi` to generate the `configure` script. This is explained in the [README.md](https://github.com/gmarcais/Jellyfish/blob/master/README.md) file.

**Comment by chjiao** [comment]
Thanks. I have successfully installed the tool based on your instructions.
