### ISSUE TITLE
can't install update

### ISSUE THREAD

**Issue by Mobean** [gmarcais/Jellyfish#78]
I have been trying to update old version on Jellyfish on a remote server.  The executable file in usr/local/bin is not updating.  I am quite a noob so this is a very green question.  I have limited experience updating programs on our linux server. I tried using the commands in readme file, but only get errors.  Any suggestions would be greatly appreciated.

colleen@Rosalind:~/REPdenovo/Jellyfish$ ./configure
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
./configure: line 3010: LT_INIT: command not found
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for md5sum... md5sum
checking for yaggo... false
./configure: line 3884: syntax error near unexpected token `VALGRIND,'
./configure: line 3884: `      PKG_CHECK_MODULES(VALGRIND, valgrind >= 1.8.0)'
colleen@Rosalind:~/REPdenovo/Jellyfish$ emacs sub_commands/info_main_cmdline.yaggo

**Comment by gmarcais** [comment]
Hi Mobean,

you should use the release tarball instead of starting from the github tree. You can dowload the tarball named `jellyfish-x.x.x.tar.gz` from [here](https://github.com/gmarcais/Jellyfish/releases). The following code should install jellyfish in `/usr/local`:

```Shell
wget https://github.com/gmarcais/Jellyfish/releases/download/v2.2.6/jellyfish-2.2.6.tar.gz
tar zxf jellyfish-2.2.6.tar.gz
cd jellyfish-2.2.6
./configure
make -j 10
sudo make install
sudo ldconfig
```

If you install in a different location where you don't need root access, for example in your $HOME, then the following is enough:

```Shell
wget https://github.com/gmarcais/Jellyfish/releases/download/v2.2.6/jellyfish-2.2.6.tar.gz
tar zxf jellyfish-2.2.6.tar.gz
cd jellyfish-2.2.6
./configure --prefix=$HOME
make -j 10
make install
```

Hope this helps.

**Comment by Mobean** [comment]
So helpful. Thanks!
