### ISSUE TITLE
2.2.6: make: *** No rule to make target 'false', needed by 'sub_commands/count_main_cmdline.hpp'.  Stop.

### ISSUE THREAD

**Issue by mmokrejs** [gmarcais/Jellyfish#87]
Hi,
  do you have an idea what is wrong in the Makefile rules?

```
checking for yaggo... false
checking for x86_64-pc-linux-gnu-pkg-config... /usr/bin/x86_64-pc-linux-gnu-pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for __int128... yes
checking for std::numeric_limits<__int128>... no
checking for _NSGetExecutablePath... no
checking for execinfo.h... yes
checking for ext/stdio_filebuf.h... yes
checking for siginfo_t.si_int... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating tests/compat.sh
config.status: creating jellyfish-2.0.pc
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
>>> Source configured.
>>> Compiling source in /scratch/var/tmp/portage/sci-biology/jellyfish-2.2.6/work/Jellyfish-2.2.6 ...
make -j2 
make: *** No rule to make target 'false', needed by 'sub_commands/count_main_cmdline.hpp'.  Stop.
```

```
$ grep false /scratch/var/tmp/portage/sci-biology/jellyfish-2.2.6/work/Jellyfish-2.2.6/Makefile
    false; \
    false; \
am__v_P_0 = false
    n|no|NO) false;; \
DLLTOOL = false
YAGGO = false
          success=false; \
        @false
$
```
Is https://github.com/gmarcais/yaggo required? Indeed, installing it fixes the problem. Please make the configure exit if yaggo is not installed.

**Comment by gmarcais** [comment]
You should download the distribution tar ball instead. It does not have a dependency on `yaggo`.
https://github.com/gmarcais/Jellyfish/releases/download/v2.2.6/jellyfish-2.2.6.tar.gz

**Comment by mmokrejs** [comment]
I want the source tarball. I am fetching ttps://github.com/gmarcais/Jellyfish/archive/v2.2.6.tar.gz . Actually, here is an update ebuild for Gentoo Linux I am merely speaking about here. ;-)

https://cgit.gentoo.org/proj/sci.git/tree/sci-biology/jellyfish/jellyfish-2.2.6.ebuild

**Comment by gmarcais** [comment]
Maybe there is a policy issue with Gentoo that I do not understand here that forces you to grab the Github generated tarball.

The tarball `jellyfish-2.2.6.tar.gz` IS a source tarball. It is THE official source distribution of Jellyfish. It contains all the normal development files that one except in an autoconf/automake package, like thousand of others. I am sure many (most?) ebuild in Gentoo work from that type of tarball.

The Github generated tarball is a copy of the git tree. It is redundant in my opinion, and it is not what the source distribution of an autoconf/automake package looks like (it has more dependencies for one).

**Comment by mmokrejs** [comment]
OK, I understand now. The https://github.com/gmarcais/Jellyfish/releases/download/v2.2.6/jellyfish-2.2.6.tar.gz URL indeed unpacks into ./jellyfish-2.2.6/, whcih is good. I still see a configure check for yaggo but `make` doe snot break later. So, you can close this issue. Thank you. (am pushing out the changes now).

**Comment by enricorox** [comment]
Now same error appears to me

> make: *** No rule to make target 'false', needed by 'sub_commands/count_main_cmdline.hpp'.  Stop.

I don't know how to solve.

OS: Ubuntu 20.04.4

**Comment by gmarcais** [comment]
@enricorox Are you working from the [jellyfish-2.3.0.tar.gz](https://github.com/gmarcais/Jellyfish/releases/download/v2.3.0/jellyfish-2.3.0.tar.gz) file, as explained above? Here is a short Dockerfile as an example how to compile and that it should work with Ubuntu 20.04. If it doesn't work for you, please send a longer bug report (URL of source downloaded, command run, platform, etc.).

```Dockerfile
FROM ubuntu:20.04

RUN apt update && \
    apt install -y build-essential yaggo wget

RUN wget https://github.com/gmarcais/Jellyfish/releases/download/v2.3.0/jellyfish-2.3.0.tar.gz && \
    tar zxf jellyfish-2.3.0.tar.gz && \
    cd jellyfish-2.3.0 && \
    ./configure && \
    make && \
    make install && \
    ldconfig
```

Then, to compile and test:

```Shell
> sudo docker build -t jellyfish .
... lots of output ...
Removing intermediate container 00ed7f4c90ee
 ---> dd4f4cfe6c85
Successfully built dd4f4cfe6c85
Successfully tagged jellyfish:latest
> sudo docker run --rm jellyfish jellyfish --help
Usage: jellyfish <cmd> [options] arg...
Where <cmd> is one of: count, bc, info, stats, histo, dump, merge, query, cite, mem, jf.
Options:
  --version        Display version
  --help           Display this message
```

**Comment by enricorox** [comment]
I've figured out I was working on JellyFish-2 master branch (https://github.com/zippav/Jellyfish-2).

Version 2.3.0 works like a charm even with source downloaded with `git clone`, thank you.
