### ISSUE TITLE
mask fastq/fasta based on low coverage kmer?

### ISSUE THREAD

**Issue by wangyugui** [gmarcais/Jellyfish#88]
Hi.
Are there some tools to mask fastq/fasta based on low coverage kmer?

**Comment by wangyugui** [comment]
I am testing Quake(http://www.cbcb.umd.edu/software/quake/manual.html)
It is based on Jellyfish.

**Comment by wangyugui** [comment]
Quake is based on jellyfish 1.  And it try to correct the wrong seq to right .

kmer-mask is the tool that I wanted, but there are some problems
- meryl is slower than Jellfish and it uses too much memory.
- some bugs need to fix for big fastq/fasta files .(I have the dirty patch(uint32->uint64), but it seems not active)

**Comment by gmarcais** [comment]
What exactly are you looking for?

**Comment by wangyugui** [comment]
a tool like kmer-mask to mask fasta/fastq file.

**Comment by gmarcais** [comment]
If you look in the example directory, there is `query_per_sequence`. The program takes in a JF database and any number of fasta/fastq files. For each k-mer in the fasta files, it prints the count from the database.

You probably can write a kmer-mask equivalent using that code.

**Comment by wangyugui** [comment]
thanks. Let's close this ticket.
