### ISSUE TITLE
make: missing aclocal

### ISSUE THREAD

**Issue by ondovb** [gmarcais/Jellyfish#90]
Got this error after configuring and running `make`:

    [jellyfish-2.2.6]$ make
    CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /home/ondovbd/jellyfish-2.2.6/missing aclocal-1.14 -I m4
    /home/ondovbd/jellyfish-2.2.6/missing: line 81: aclocal-1.14: command not found
    WARNING: 'aclocal-1.14' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
    make: *** [aclocal.m4] Error 127

Running `autoreconf` seems to resolve the issue.

**Comment by gmarcais** [comment]
Is this from the distribution tar ball [jellyfish-2.2.6.tar.gz](https://github.com/gmarcais/Jellyfish/releases/download/v2.2.6/jellyfish-2.2.6.tar.gz) or from the git tree?

If it is from the git tree, then yes, you need to run `autoreconf -i` before you can issue `make`. Unless you plan to develop for Jellyfish, you should use the distribution tar ball which contains everything you need to compile and install.

**Comment by ondovb** [comment]
What's strange is that there was initially a `configure` script, which of course is not even in the source tree. Maybe the distribution was untarred over a source folder, or something like that. Anyway, I can't get it to happen again from a fresh download.
