### ISSUE TITLE
How to remove jellyfish 2 from my machine?

### ISSUE THREAD

**Issue by falkomathes** [gmarcais/Jellyfish#92]
Hi guys,

I installed jellyfish version 2.2.6 to be used by Kraken. However, Kraken needs jellyfish version 1 which I then also installed (version 1.1.11) but Kraken seems to only "see" jellyish 2.2.6.

So, how can I uninstall / remove jellyfish 2 from my machine in favour of jellyfish 1?

Thanks and all the best,
Falko

**Comment by gmarcais** [comment]
The Makefile in Jellyfish is created by autoconf/automake. It has an 'uninstall' target. So `make uninstall` from the compilation directory should do the trick (you might need sudo).

If this does not work, you might have to remove it "by hand". I would need more information of where you installed the software: what does `which -a jellyfish` returns?
