### ISSUE TITLE
numeric parsing treats empty string as legit zero (ought to be an error?)

### ISSUE THREAD

**Issue by rsharris** [gmarcais/Jellyfish#93]
Many old-time *nix folks will probably think this report is silly, but ...

Some (if not all) of the command line parsing of numbers doesn't reject an empty string.  So, for example, if you do `jellyfish dump --lower-count=${threshold} foo.jf` and you've neglected to set `threshold`, jellyfish will happily give you all kmers (since it thinks you wanted lower-count=0).

Admittedly this is a user error, but it would be simple to check for it. And the consequence to downstream results can be pretty drastic and difficult to notice.

I note that the code (e.g. dump_main_cmdline.hpp) seems to expect strtoull to detect some errors and report them by setting errno:
```
template<typename T>
  static T conv_uint(const char *str, ::std::string &err, bool si_suffix) {
     ...
    errno = 0;
     ...
    unsigned long long int res = strtoull(str, &endptr, 0);
    if(errno) {
      err.assign(strerror(errno));
      return (T)0;
    }
     ...
```
but strtoull apparently doesn't reject empty strings. I've tried to find a spec that indicates what strtoull _will_ reject. No luck except for a stackOverflow post saying strtoull uses errno to report out-of-range errors but not necessarily parsing issues. Perhaps empty strings give different behavior on different platforms.

**Comment by gmarcais** [comment]
I update yaggo to check for this type of error. The next release of Jellyfish will have that feature.
