### ISSUE TITLE
Jellyfish stalling when counting 7, 8 mers on large files 

### ISSUE THREAD

**Issue by cjfiscus** [gmarcais/Jellyfish#95]
I'm currently using jellyfish to count K-mers in assembled genomes. 

I'm able to count 5, 6 and 10-20 mers without any problem, but for some reason the program creates hundreds of small subfiles when counting 7, 8, and 9 mers. Additionally, the program fails to give output with a cannot merge hash of different size error.  

Initially I thought this was a problem with hash size.  I've increased the hash to 100G and am still having the same issue.

**Comment by yanazima** [comment]
Hey cjfiscus,
were you ever able to resolve this issue? I am having exactly same problem.
Will greatly appreciate your response.
Thank you!

**Comment by cjfiscus** [comment]
Hi yanazima, 

No. I ended up switching to another K-mer counter.

**Comment by yanazima** [comment]
You mean another k-value or another software?

**Comment by cjfiscus** [comment]
Another software. I switched to dsk https://github.com/GATB/dsk however it only counts "canonical" mers.

**Comment by yanazima** [comment]
Thank you so much for your response!

**Comment by kpalin** [comment]
Me too.

Jellyfish counts 1692415 9mers in 0.31 seconds and 2426647 6mers in 0.26 seconds but for 7mers, it happily allocates 192GB memory in 1 minute 10 seconds before I killed it.

The command lines were like (-m argument variable)
```
$ zcat HNF4A_TGACAG20NGA_AF_1.fastq.gz | /usr/bin/time -v jellyfish count -o test.jf --text -m 7 -s 1M --bf-size 1G -t 16 /dev/stdin
```
the input file contains 162166 20bp reads.

**Comment by cjfiscus** [comment]
I found I can circumvent the memory usage problem by using the --disk flag.

**Comment by kpalin** [comment]
I can confirm the '--disk' workaround works and 7 and 8 mer counting happens in 0.73 seconds and 1.3GB memory (Maximum resident sent size).   This with jellyfish version 2.2.6 installed from bioconda.

**Comment by yanazima** [comment]
Could you please post a sample command line that you run for counting 8mers with using —disk flag?
Thank you!

Yana Hrytsenko

**Comment by kpalin** [comment]
It was just
```
zcat HNF4A_TGACAG20NGA_AF_1.fastq.gz | /usr/bin/time -v jellyfish count -o test.jf --text -m 7 -s 1M --bf-size 1G -t 16 --disk /dev/stdin
```

**Comment by yanazima** [comment]
Thank you so much!

Yana Hrytsenko

**Comment by gmarcais** [comment]
Version 2.2.8 fixes that issue. Almost released.

**Comment by ngarud** [comment]
Hi I'm using Jellyfish 2.2.6 Bioconda and had the same issue with the program aborting whenever I'd run 7mers. However, the --disk flag seems to help take care of the early ending issue. The problem is that the kmer counts are always less than expected when using Jellyfish 2.2.6 Bioconda. I get larger kmer counts when I use Jellyfish 2.2.9. This makes me suspect that something is not going correctly with the merge or the writing disk. 

The reason why I have to use Jellyfish 2.2.6 Bioconda is I cannot install Jellyfish 2.2.9 on my university cluster (too many dependencies needed).

**Comment by ngarud** [comment]
Sorry -- I just figured out that Jellyfish 2.2.6 Bioconda is outputting kmers in a different order (non-alphabetically) than Jellyfish 2.2.9, hence the discrepancies in counts. Any reason why this is the order is chagned? Is there a way to output kmers alphabetically using the Bioconda version?
