### ISSUE TITLE
Is there a way to build jellyfish statically linking libraries? 

### ISSUE THREAD

**Issue by jregalad** [gmarcais/Jellyfish#97]
I tried with:

 CXXFLAGS = -static

but it didn't work. 

I need this because I am in a system with old C libraries.

**Comment by gmarcais** [comment]
Do: `./configure --enable-all-static`. If compilation fails, you may have to change `-lpthread` to `-pthread` in the Makefile, in the `AM_LDFLAGS` variable.

**Comment by jregalad** [comment]
Works like a charm!!!
Thanks
